# Docker Compose Version
version: '3.8'

# The services in your project
services:
  # FastAPI Application
  fastapi:
    build:
      context: ./fastapi-docker # Path to your Dockerfile
      dockerfile: Dockerfile # Name of your Dockerfile
    container_name: fastapi-docker-container # Name of the container
    ports:
      - "8000:8000" # Expose port 8000 on the host to port 8000 in the container
    restart: unless-stopped # Restart the container if it stops, you can declare policies in it like, restart it at 12:05 AM because a new codebase is updated at 12:00 AM etc.
    networks: # Doing a communication between containers
      - app-networks
  
  # Next.js Application
  nextjs:
    build:
      context: ./nextjs-docker # Path to your Dockerfile
      dockerfile: Dockerfile # Name of your Dockerfile
    container_name: nextjs-docker-container # Name of the container
    ports:
      - "3000:3000" # Expose port 3000 on the host to port 3000 in the container
    restart: unless-stopped # Restart the container if it stops, you can declare policies in it like, restart it at 12:05 AM because a new codebase is updated at 12:00 AM etc.
    networks: # Doing a communication between containers
      - app-networks

# Networks
networks:
  app-networks:
    driver: bridge